spring:
  application:
    name: flowrunner

flowrunner:
  flow:
    dimensions:
      - key: environment
        name: Environment
        defaultValue: local
        required: true
        children:
          - key: application
            name: Application
            required: true
            children:
              - key: channel
                name: Channel
                defaultValue: Web
                required: false
    instance:
      environment:
        value: dev
        application:
          value: Customer
          channel:
            value: Web
