spring:
  application:
    name: Flowrunner

server:
  port: 8080

flowrunner:
  flow:
    validate-on-startup: true
    dimensions:
      - key: environment
        name: Environment
        defaultValue: local
        required: true
        children:
          - key: application
            name: Application
            required: true
            children:
              - key: channel
                name: Channel
                defaultValue: web
                required: false
    configuration:
      - dimension: environment
        key: local
        name: Local Environment
        children:
          - dimension: application
            key: customer
            name: Customer
            children:
              - dimension: channel
                key: web
                name: Web
              - dimension: channel
                key: mob
                name: Mobile
          - dimension: application
            key: backoffice
            name: Backoffice
            children:
              - dimension: channel
                key: web
                name: Web
      - dimension: environment
        key: platform-dev
        name: Platform Development Environment
        children:
          - dimension: application
            key: customer
            name: Customer
            children:
              - dimension: channel
                key: web
                name: Web
              - dimension: channel
                key: mob
                name: Mobile
          - dimension: application
            key: backoffice
            name: Backoffice
            children:
              - dimension: channel
                key: web
                name: Web